apiVersion: v1
kind: Service
metadata:
  name: {{ include "cas-server.bootadminname" . }}
  labels:
    {{- include "cas-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cas-bootadmin.selectorLabels" . | nindent 4 }}
