apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cas-server.fullname" . }}-scripts
  labels: {{- include "cas-server.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    #!/bin/sh
    echo Working Directory: $(pwd)
    echo java -server -noverify $MAX_HEAP_OPT $NEW_HEAP_OPT $JVM_EXTRA_OPTS -jar $CAS_WAR $@
    exec java -server -noverify $MAX_HEAP_OPT $NEW_HEAP_OPT $JVM_EXTRA_OPTS -jar $CAS_WAR $@
